plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.yeling'
version = '1.0.2'
description = 'yelingzi-blog'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
    maven {
        name = 'Central Portal Snapshots'
        url = 'https://central.sonatype.com/repository/maven-snapshots/'
    }
}

def buildTimestamp = new Date().format('yyyyMMddHHmmss')

bootJar {
    archiveBaseName = 'yelingziBlog'
    archiveVersion = "${project.version}-${buildTimestamp}"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    implementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation 'io.jsonwebtoken:jjwt:0.12.5'
    implementation 'com.alibaba:fastjson:2.0.9.graal'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'io.netty:netty-all'
    implementation 'com.github.whvcse:easy-captcha:1.6.2'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'com.github.houbb:sensitive-word:0.24.0'
    implementation 'org.lionsoul:ip2region:2.7.0'
    implementation 'org.commonmark:commonmark:0.24.0'
    implementation 'com.github.ben-manes.caffeine:caffeine'
//    implementation platform("org.springframework.ai:spring-ai-bom:1.0.2")
//    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation platform("com.alibaba.cloud.ai:spring-ai-alibaba-bom:1.0.0.2")
    implementation 'com.alibaba.cloud.ai:spring-ai-alibaba-starter-dashscope'
    implementation 'com.alibaba:easyexcel:4.0.3'
    implementation 'org.apache.commons:commons-compress:1.28.0'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation 'org.apache.poi:poi-ooxml:5.5.0'


    compileOnly 'org.projectlombok:lombok'
    implementation 'org.jsoup:jsoup:1.17.2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
